const users = [{
    "id": 1,
    "first_name": "Georg",
    "last_name": "Loudian",
    "email": "gloudian0@msu.edu",
    "gender": "Genderqueer",
    "password": "123456789"
  }, {
    "id": 2,
    "first_name": "Lark",
    "last_name": "O'Scollee",
    "email": "loscollee1@boston.com",
    "gender": "Agender",
    "password": "123456789"
  }, {
    "id": 3,
    "first_name": "Binni",
    "last_name": "Blazey",
    "email": "bblazey2@lulu.com",
    "gender": "Bigender",
    "password": "123456789"
  }, {
    "id": 4,
    "first_name": "Greer",
    "last_name": "McQuarrie",
    "email": "gmcquarrie3@icq.com",
    "gender": "Non-binary",
    "password": "123456789"
  }, {
    "id": 5,
    "first_name": "Lebbie",
    "last_name": "Hizir",
    "email": "lhizir4@ocn.ne.jp",
    "gender": "Genderfluid",
    "password": "123456789"
  }, {
    "id": 6,
    "first_name": "Ardyth",
    "last_name": "Tuhy",
    "email": "atuhy5@multiply.com",
    "gender": "Male",
    "password": "123456789"
  }, {
    "id": 7,
    "first_name": "Raffaello",
    "last_name": "McKendo",
    "email": "rmckendo6@archive.org",
    "gender": "Agender",
    "password": "123456789"
  }, {
    "id": 8,
    "first_name": "Tim",
    "last_name": "Brandes",
    "email": "tbrandes7@taobao.com",
    "gender": "Bigender",
    "password": "123456789"
  }, {
    "id": 9,
    "first_name": "Hoebart",
    "last_name": "Vlahos",
    "email": "hvlahos8@eepurl.com",
    "gender": "Bigender",
    "password": "123456789"
  }, {
    "id": 10,
    "first_name": "Benny",
    "last_name": "Klimschak",
    "email": "bklimschak9@shinystat.com",
    "gender": "Non-binary",
    "password": "123456789"
  }]


  module.exports = users;
  