GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYzNzkwOTYwMX0.42hqHiYbkM18l-0_5Ro_DgXuNtZayOvtzVjUPImXKZg

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Kyle"
}